version: '3.5'

networks:
  # Network for api gateway
  network-gateway:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.2.0/24
  # Network for microservices
  network-microservice:
    #internal: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.4.0/24

services:
  db:
   image: mcr.microsoft.com/mssql/server:2019-latest
   container_name: db
   restart: on-failure
   environment:
    - "ACCEPT_EULA=Y"
    - "SA_PASSWORD=pass123!"
   ports:
    - "1433:1433"
   networks:
    - network-microservice

  mongo:
    image: mongo
    container_name: mongo
    restart: on-failure
    ports:
      - "27017:27017"
    networks:
      - network-microservice

  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
   container_name: elasticsearch
   restart: on-failure
   ports:
    - "9200:9200"
   environment:
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - "discovery.type=single-node"
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   networks:
    - network-microservice

  kibana:
   image: docker.elastic.co/kibana/kibana:7.8.1
   container_name: kibana
   restart: on-failure
   ports:
    - "5601:5601"
   depends_on:
    - elasticsearch
   networks:
    - network-microservice

  apm:
   image: docker.elastic.co/apm/apm-server:7.8.1
   container_name: apm
   restart: on-failure
   ports:
    - "8200:8200"
   depends_on:
    - kibana
   networks:
    - network-microservice

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: on-failure
    environment:
     - RABBITMQ_DEFAULT_USER=user
     - RABBITMQ_DEFAULT_PASS=password
    ports:
     - "5672:5672"
     - "15672:15672"
    networks:
     - network-microservice

  consul:
    image: consul
    container_name: consul
    restart: on-failure
    volumes:
    - consul-data:/consul/config
    ports:
     - "8500:8500"
    networks:
     - network-microservice

volumes:
  elasticsearch-data:
  consul-data:
